# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca5bb5daeb0a2414f5ff919825fec19c66b02abb0bd666edfff9334c5809149ad998fe2b5d7faa8fd93bb22de32d87a1815cabf3ce92795d6cafa26573f06c4e
  db_username: finapp
  db_password: abc123
  google_client_id: 223228915402-akv2cq6dpbg1th4eojb0ufbva7l3o183.apps.googleusercontent.com
  google_client_secret: rQqvzxEP9ZlKbNBwSTwP0fjG
  email_password: fatec123
  email_username: finapp.fatec
  messages_email_password: fatec123

test:
  secret_key_base: 99ee1b53585817550aa6d651cf67c342c9da244bc10ab9498cf3084f2d8fc790caee5d01cd3ef64ec024d93571c61b2024002a9cb1b705201c17ad8a2e5c131b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: f7757572154c911c56e664bc316cdc31ef7bace0ff061dfcaefa47c67a8d8bd64933b2ecbbbea1eb52116964daf313bf2998b422b3589e1afa056b579fc414e8
  db_username: finapp
  db_password: abc123
  google_client_id: 223228915402-akv2cq6dpbg1th4eojb0ufbva7l3o183.apps.googleusercontent.com
  google_client_secret: rQqvzxEP9ZlKbNBwSTwP0fjG
  email_password: fatec123
  email_username: finapp.fatec
  messages_email_password: fatec123